version: '3.9'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 InvoiceGenerator.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=InvoiceGenerator.settings

volumes:
  static_volume: 