app = "InvoiceGenerator"

[build]
  dockerfile = "Dockerfile"

[env]
  DJANGO_SECRET_KEY = "django-insecure-9e5*i8w(ffjmv-rae%&x4%$xb6o^2_#9(kp*mi3*#c1@q8sgbw"
  DJANGO_DEBUG = "false"
  DATABASE_URL = "sqlite:///db.sqlite3"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
