services:
  - name: creamtop
    type: web
    env: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn InvoiceGenerator.asgi:application -k uvicorn.workers.UvicornWorker"
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"  # Change if using PostgreSQL
      - key: DJANGO_DEBUG
        value: "false"
    healthCheckPath: /
    autoDeploy: true