services:
  - name: creamtop
    type: web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn InvoiceGenerator.wsgi:application --workers 4 --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: DJANGO_DEBUG
        value: "false"
    healthCheckPath: /
    autoDeploy: true