services:
  - name: creamtop
    type: web
    env: python
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"  # Change if using PostgreSQL
      - key: DJANGO_DEBUG
        value: "false"
    healthCheckPath: /
    autoDeploy: true
