# Generated by Django 5.1.4 on 2025-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_email_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, help_text='15-digit GST number (e.g., 22AAAAA0000A1Z5)', max_length=15, null=True),
        ),
    ]
